[package]
name = "AdventOfCode"
version = "0.1.0"
edition = "2021"

[[bench]]
name = "bench"
path = "src/bench.rs"
harness = false

[dependencies]
criterion = { version =  "0.5", features = ["html_reports"] }
log = "0.4.25"